[project]
name = "color50"
version = "1.0.0"
authors = [
    { name="Daniel Fletcher", email="dfletcher-mail@proton.me" }
]
description = "Placeholder description"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.urls]
Homepage = "https://github.com/danielthefletch/color50"
